from ai_economist.foundation.base.base_env import component_registry

from aie.environments.Italian_tax_brackets_env import ItalianPeriodicBracketTax

component_registry.add(ItalianPeriodicBracketTax)
